ApiCliente/Controllers/TicketController.cs
using ApiCliente.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace ApiCliente.Controllers
{
    public class TicketController : Controller
    {
        // GET: Ticket
        public ActionResult Index()
        {
			IEnumerable<mvcTicketModel> contList;
			HttpResponseMessage response = GlobalVariables.WebApiTicket.GetAsync("Tickets").Result;
			contList = response.Content.ReadAsAsync<IEnumerable<mvcTicketModel>>().Result;
			return View(contList);
		}
		public ActionResult ListarClientes()
		{
			IEnumerable<mvcClienteModel> contList;
			HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("Clientes").Result;
			contList = response.Content.ReadAsAsync<IEnumerable<mvcClienteModel>>().Result;
			return PartialView(contList);
		}
		public ActionResult AgregarOEditar(int id = 0)
		{
			if (id == 0)
				return View(new mvcTicketModel());
			else
			{
				HttpResponseMessage response = GlobalVariables.WebApiTicket.GetAsync("Tickets/" + id.ToString()).Result;
				return View(response.Content.ReadAsAsync<mvcTicketModel>().Result);
			}
		}
		[HttpPost]
		public ActionResult AgregarOEditar(mvcTicketModel contc)
		{
			if (contc.Id == 0)
			{
				HttpResponseMessage response = GlobalVariables.WebApiTicket.PostAsJsonAsync("Tickets", contc).Result;
				TempData["SuccessMessage"] = "Exito al Guardar";
			}
			else
			{
				HttpResponseMessage response = GlobalVariables.WebApiTicket.PutAsJsonAsync("Tickets/" + contc.Id, contc).Result;
				TempData["SuccessMessage"] = "Exito al Modificar";
			}

			return RedirectToAction("Index");

		}
		public ActionResult Eliminar(int id)
		{
			HttpResponseMessage response = GlobalVariables.WebApiTicket.DeleteAsync("Tickets/" + id.ToString()).Result;
			TempData["SuccessMessage"] = "Eliminado Exitosamente";
			return RedirectToAction("Index");
		}
	}
}

ApiCliente/Views/Ticket/AgregarOEditar.cshtml
@model ApiCliente.Models.mvcTicketModel
@{
	ViewBag.Title = "Mantenimiento de Tickets";
}

<h2>Mantenimiento de Tickets</h2>


<div class="form-body">

	@using (Html.BeginForm())
	{
		@Html.HiddenFor(Model => Model.Id)

		<div class="form-group">
			@Html.LabelFor(Model => Model.Titulo_Problema)
			@Html.EditorFor(Model => Model.Titulo_Problema)
			@Html.ValidationMessageFor(Model => Model.Titulo_Problema)
		</div>

		<div class="form-group">
			@Html.LabelFor(Model => Model.Detalle)
			@Html.EditorFor(Model => Model.Detalle)
			@Html.ValidationMessageFor(Model => Model.Detalle)
		</div>

		<div class="form-group">
			@Html.LabelFor(Model => Model.Reporta)
			@Html.EditorFor(Model => Model.Reporta)
			@Html.ValidationMessageFor(Model => Model.Reporta)
		</div>

		<div class="form-group" id="SelectHouse">
			@Html.LabelFor(Model => Model.Cliente)
			@Html.Action("ListarClientes", "Ticket");
			@Html.ValidationMessageFor(Model => Model.Cliente)
		</div>

		<div class="form-group">
			@Html.LabelFor(Model => Model.EstadoActual)
			<select class="form-control" id="EstadoActual" name="EstadoActual">
				<option value="Abierto">Abierto</option>
				<option value="En Proceso">En Proceso</option>
				<option value="En Espera">En Espera</option>
				<option value="Finalizado">Finalizado</option>
			</select>
			@Html.ValidationMessageFor(Model => Model.EstadoActual)
		</div>

		<div class="form-group">
			<input type="submit" value="Guardar" class="btn button" />
			<input type="reset" value="Limpiar" class="btn button" />
		</div>

	}

</div>

<script>
	$('.SelectHouse').click(function() {

 $.ajax({  url: @Url.Action("ListarClientes", "Ticket"),
           type: "post",
           dataType:"html",
           data: "<your data as serialized json>
	",
	success: function(result) {
	$('.divForSelectHouse').html(result);
	}
	});
	});
</script>

ApiCliente/Views/Ticket/Index.cshtml
@model IEnumerable<ApiCliente.Models.mvcTicketModel>

@{
	ViewBag.Title = "Menú Tickets";
}
<br>
<h2>Menú Tickets</h2>

<p>
	<a href="@Url.Action("AgregarOEditar", "Ticket")" class="btn btn-default"><i class="fa fa-plus"></i> Agregar Nuevo</a>
</p>
<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Titulo_Problema)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Detalle)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Reporta)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Cliente)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.EstadoActual)
		</th>
		<th></th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.Titulo_Problema)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Detalle)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Reporta)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Cliente1.Nombre)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.EstadoActual)
			</td>
			<td>
				<a href="@Url.Action("AgregarOEditar", "Ticket", new { id= item.Id})" class="btn btn-default"><i class="fa fa-pencil"></i> Editar</a>

				<a Onclick="Delete(@item.Id)" class="btn btn-default"><i class="fa fa-trash"></i> Eliminar</a>
			</td>
		</tr>
	}

</table>


@section Scripts {
	<script>
	$(function () {
            var successMessage = '@TempData["SuccessMessage"]'
            if (successMessage != '')
                alertify.success(successMessage);
	});
	function Delete(id) {
            alertify.confirm('Web Api CRUD','Realmente desea eliminar el registro ?',function(){
                window.location.href  = '@Url.Action("Eliminar", "Ticket")/'+id;
            },null );
    }
	</script>

}

ApiCliente/Views/Ticket/ListarClientes.cshtml
@model IEnumerable<ApiCliente.Models.mvcClienteModel>

<select class="form-control" id="Cliente" name="Cliente">
	@foreach (var item in Model)
	{
		<option value="@item.id"> @item.Nombre</option>
	}
</select>