ApiCliente/Controllers/UsuarioController.cs
using ApiCliente.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace ApiCliente.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
			IEnumerable<mvcUsuarioModel> usuList;
			HttpResponseMessage response = GlobalVariables.WebApiUsuario.GetAsync("Usuarios").Result;
			usuList = response.Content.ReadAsAsync<IEnumerable<mvcUsuarioModel>>().Result;
			return View(usuList);
		}

		public ActionResult AgregarOEditar(int id = 0)
		{
			if (id == 0)
				return View(new mvcUsuarioModel());
			else
			{
				HttpResponseMessage response = GlobalVariables.WebApiUsuario.GetAsync("Usuarios/" + id.ToString()).Result;
				return View(response.Content.ReadAsAsync<mvcUsuarioModel>().Result);
			}
		}
		[HttpPost]
		public ActionResult AgregarOEditar(mvcUsuarioModel usu)
		{
			if (usu.Id == 0)
			{
				HttpResponseMessage response = GlobalVariables.WebApiUsuario.PostAsJsonAsync("Usuarios", usu).Result;
				TempData["SuccessMessage"] = "Exito al Guardar";
			}
			else
			{
				HttpResponseMessage response = GlobalVariables.WebApiUsuario.PutAsJsonAsync("Usuarios/"+usu.Id, usu).Result;
				TempData["SuccessMessage"] = "Exito al Modificar";
			}
			return RedirectToAction("Index");

		}
		public ActionResult Eliminar(int id)
		{
			HttpResponseMessage response = GlobalVariables.WebApiUsuario.DeleteAsync("Usuarios/" + id.ToString()).Result;
			TempData["SuccessMessage"] = "Eliminado Exitosamente";
			return RedirectToAction("Index");
		}
	}
}

ApiCliente/Views/Usuario/AgregarOEditar.cshtml
@model ApiCliente.Models.mvcUsuarioModel


@{
	ViewBag.Title = "AgregarOEditar";
}

<h2>Mantenimiento de Usuarios</h2>

<div class="form-body">
	@using (Html.BeginForm())
	{
		@Html.HiddenFor(Model => Model.Id)

		<div class="form-group">
			@Html.LabelFor(Model => Model.Nombre_Usuario)
			@Html.EditorFor(Model => Model.Nombre_Usuario)
			@Html.ValidationMessageFor(Model => Model.Nombre_Usuario)
		</div>

		<div class="form-group">
			@Html.LabelFor(Model => Model.Apellido_Usuario)
			@Html.EditorFor(Model => Model.Apellido_Usuario)
			@Html.ValidationMessageFor(Model => Model.Apellido_Usuario)
		</div>

		<div class="form-group">
			@Html.LabelFor(Model => Model.Contrasena)
			@Html.EditorFor(Model => Model.Contrasena)
			@Html.ValidationMessageFor(Model => Model.Contrasena)
		</div>

		<div class="form-group">
			@Html.LabelFor(Model => Model.Rol_Usuario)
			<select class="form-control" id="Rol_Usuario" name="Rol_Usuario">
				<option value="Admin">Administrador</option>
				<option value="User">Usuario</option>
			</select>
			@Html.ValidationMessageFor(Model => Model.Rol_Usuario)
		</div>
		<br>
		<div class="form-group">
			<input type="submit" value="Guardar" class="btn button" />
			<input type="reset" value="Limpiar" class="btn button" />
		</div>
	}
</div>

@section scripts{
	@Scripts.Render("~/bundles/jqueryval");
}

ApiCliente/Views/Usuario/Index.cshtml
@model IEnumerable<ApiCliente.Models.mvcUsuarioModel>

@{
	ViewBag.Title = "Menú Usuarios";
}
<br>
<h2>Menú Usuarios</h2>


<p>
	<a href="@Url.Action("AgregarOEditar", "Usuario")" class="btn btn-default"><i class="fa fa-plus"></i> Agregar Nuevo</a>
</p>
<table class="table table-striped">
	<thead class="table-heading">
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Nombre_Usuario)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Apellido_Usuario)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Rol_Usuario)
			</th>

			<th>Acciones</th>
		</tr>
	</thead>
	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.Nombre_Usuario)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Apellido_Usuario)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Rol_Usuario)
			</td>

			<td>
				<a href="@Url.Action("AgregarOEditar", "Usuario", new { id= item.Id})" class="btn btn-default"><i class="fa fa-pencil"></i> Editar</a>

				<a Onclick="Delete(@item.Id)" class="btn btn-default"><i class="fa fa-trash"></i> Eliminar</a>
			</td>
		</tr>
	}

</table>
@section Scripts {
	<script>
	$(function () {
            var successMessage = '@TempData["SuccessMessage"]'
            if (successMessage != '')
                alertify.success(successMessage);
	});
	function Delete(id) {
            alertify.confirm('Web Api CRUD','Realmente desea eliminar el registro ?',function(){
                window.location.href  = '@Url.Action("Eliminar","Usuario")/'+id;
            },null );
    }
	</script>
}