ApiCliente/Controllers/ReunionController.cs
using ApiCliente.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace ApiCliente.Controllers
{
    public class ReunionController : Controller
    {
        // GET: Reunion
        public ActionResult Index()
        {
			IEnumerable<mvcReunionModel> reunList;
			HttpResponseMessage response = GlobalVariables.WebApiReunion.GetAsync("Reuniones").Result;
			reunList = response.Content.ReadAsAsync<IEnumerable<mvcReunionModel>>().Result;
			return View(reunList);
		}

		public ActionResult ListarUsuarios()
		{
			IEnumerable<mvcUsuarioModel> contList;
			HttpResponseMessage response = GlobalVariables.WebApiUsuario.GetAsync("Usuarios").Result;
			contList = response.Content.ReadAsAsync<IEnumerable<mvcUsuarioModel>>().Result;
			return PartialView(contList);
		}

		public ActionResult AgregarOEditar(int id = 0)
		{
			if (id == 0)
				return View(new mvcReunionModel());
			else
			{
				HttpResponseMessage response = GlobalVariables.WebApiReunion.GetAsync("Reuniones/" + id.ToString()).Result;
				return View(response.Content.ReadAsAsync<mvcReunionModel>().Result);
			}
		}

		[HttpPost]
		public ActionResult AgregarOEditar(mvcReunionModel usu)
		{
			if (usu.Id == 0)
			{
				HttpResponseMessage response = GlobalVariables.WebApiReunion.PostAsJsonAsync("Reuniones", usu).Result;
				TempData["SuccessMessage"] = "Exito al Guardar";
			}
			else
			{
				HttpResponseMessage response = GlobalVariables.WebApiReunion.PutAsJsonAsync("Reuniones/" + usu.Id, usu).Result;
				TempData["SuccessMessage"] = "Exito al Modificar";
			}
			return RedirectToAction("Index");

		}
		public ActionResult Eliminar(int id)
		{
			HttpResponseMessage response = GlobalVariables.WebApiReunion.DeleteAsync("Reuniones/" + id.ToString()).Result;
			TempData["SuccessMessage"] = "Eliminado Exitosamente";
			return RedirectToAction("Index");
		}
	}
}

ApiCliente/Views/Reunion/AgregarOEditar.cshtml
@model ApiCliente.Models.mvcReunionModel
@{
	ViewBag.Title = "Mantenimiento de Reuniones";
}

<h2>Mantenimiento de Reuniones</h2>

<div class="form-body">
	@using (Html.BeginForm())
	{
		@Html.HiddenFor(Model => Model.Id)

		<div class="form-group">
			@Html.LabelFor(Model => Model.Titulo_Reunion)
			@Html.EditorFor(Model => Model.Titulo_Reunion)
			@Html.ValidationMessageFor(Model => Model.Titulo_Reunion)
		</div>

		<div class="form-group">
			@Html.LabelFor(Model => Model.Fecha_Hora)
			@Html.EditorFor(Model => Model.Fecha_Hora, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(Model => Model.Fecha_Hora)
		</div>

		<div class="form-group" id="SelectHouse">
			@Html.LabelFor(Model => Model.Id_Usuario)
			@Html.Action("ListarUsuarios", "Reunion");
			@Html.ValidationMessageFor(Model => Model.Id_Usuario)
		</div>

		<div class="form-group">
			@Html.LabelFor(Model => Model.Virtual)
			@Html.EditorFor(Model => Model.Virtual)
			@Html.ValidationMessageFor(Model => Model.Virtual)
		</div>
		<div class="form-group">
			<input type="submit" value="Guardar" class="btn button" />
			<input type="reset" value="Limpiar" class="btn button" />
		</div>
	}
</div>

<script>
	$('.SelectHouse').click(function() {

 $.ajax({  url: @Url.Action("ListarUsuarios", "Reunion"),
           type: "post",
           dataType:"html",
           data: "<your data as serialized json>
	",
	success: function(result) {
	$('.divForSelectHouse').html(result);
	}
	});
	});
</script>
@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
	$(function () {
		$('#datetimepicker2').datetimepicker({
			locale: 'ru'
		});
	});
</script>

ApiCliente/Views/Reunion/Index.cshtml
@model IEnumerable<ApiCliente.Models.mvcReunionModel>

@{
	ViewBag.Title = "Menú Reuniones";
}
<br>
<h2>Menú Reuniones</h2>

<p>
	<a href="@Url.Action("AgregarOEditar", "Reunion")" class="btn btn-default"><i class="fa fa-plus"></i> Agregar Nuevo</a>
</p>
<table class="table table-striped">
	<thead class="table-heading">
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Titulo_Reunion)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Fecha_Hora)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Id_Usuario)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Virtual)
			</th>
			<th>Acciones</th>
		</tr>
	</thead>
	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.Titulo_Reunion)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Fecha_Hora)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Usuario.Nombre_Usuario)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Virtual)
			</td>
			<td>
				<a href="@Url.Action("AgregarOEditar", "Reunion", new { id= item.Id})" class="btn btn-default"><i class="fa fa-pencil"></i> Editar</a>

				<a Onclick="Delete(@item.Id)" class="btn btn-default"><i class="fa fa-trash"></i> Eliminar</a>
			</td>
		</tr>
	}

</table>

@section Scripts {
	<script>
	$(function () {
            var successMessage = '@TempData["SuccessMessage"]'
            if (successMessage != '')
                alertify.success(successMessage);
	});
	function Delete(id) {
            alertify.confirm('Web Api CRUD','Realmente desea eliminar el registro ?',function(){
                window.location.href  = '@Url.Action("Eliminar","Reunion")/'+id;
            },null );
    }
	</script>

}

ApiCliente/Views/Reunion/ListarUsuarios.cshtml
@model IEnumerable<ApiCliente.Models.mvcUsuarioModel>

<select class="form-control" id="Id_Usuario" name="Id_Usuario">
	@foreach (var item in Model)
	{ 
		<option value="@item.Id"> @item.Nombre_Usuario </option>
	}
</select>