ApiCliente/Controllers/ClienteController.cs
using ApiCliente.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace ApiCliente.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {
			IEnumerable<mvcClienteModel> cliList;
			HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("Clientes").Result;
			cliList = response.Content.ReadAsAsync<IEnumerable<mvcClienteModel>>().Result;
			return View(cliList);
        }

		public ActionResult AgregarOEditar(int id=0)
		{
			if (id == 0)
				return View(new mvcClienteModel());
			else {
				HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("Clientes/"+id.ToString()).Result;
				return View(response.Content.ReadAsAsync<mvcClienteModel>().Result);
			}
			
		}
		[HttpPost]
		public ActionResult AgregarOEditar(mvcClienteModel cli)
		{
			if (cli.id==0)
			{
				HttpResponseMessage response = GlobalVariables.WebApiClient.PostAsJsonAsync("Clientes", cli).Result;
				TempData["SuccessMessage"] = "Exito al Guardar";
			}
			else
			{
				HttpResponseMessage response = GlobalVariables.WebApiClient.PutAsJsonAsync("Clientes/"+cli.id , cli).Result;
				TempData["SuccessMessage"] = "Exito al Modificar";
			}
			
			return RedirectToAction("Index");
			
		}
		public ActionResult Eliminar(int id)
		{
			HttpResponseMessage response = GlobalVariables.WebApiClient.DeleteAsync("Clientes/" + id.ToString()).Result;
			TempData["SuccessMessage"] = "Eliminado Exitosamente";
			return RedirectToAction("Index");
		}
	}
}

ApiCliente/Views/Cliente/AgregarOEditar.cshtml
@model ApiCliente.Models.mvcClienteModel

@{
	ViewBag.Title = "Mantenimiento de Clientes";
}

<h2>Mantenimiento de Clientes</h2>

<div class="form-body">
	@using (Html.BeginForm())
	{
		@Html.HiddenFor(Model => Model.id)

		<div class="form-group">
			@Html.LabelFor(Model => Model.Nombre)
			@Html.EditorFor(Model => Model.Nombre)
			@Html.ValidationMessageFor(Model => Model.Nombre)
		</div>

		<div class="form-group">
			@Html.LabelFor(Model => Model.Ced_Juridica)
			@Html.EditorFor(Model => Model.Ced_Juridica)
			@Html.ValidationMessageFor(Model => Model.Ced_Juridica)
		</div>
		<div class="form-group">
			@Html.LabelFor(Model => Model.Pag_Web)
			@Html.EditorFor(Model => Model.Pag_Web)
			@Html.ValidationMessageFor(Model => Model.Pag_Web)
		</div>
		<div class="form-group">
			@Html.LabelFor(Model => Model.Telefono)
			@Html.EditorFor(Model => Model.Telefono)
			@Html.ValidationMessageFor(Model => Model.Telefono)
		</div>
		<div class="form-group">
			@Html.LabelFor(Model => Model.Sector)
			<select class="form-control" id="Sector" name="Sector">
				<option value="Educacion">Educacion</option>
				<option value="Industria">Industria</option>
				<option value="Agricultura">Agricultura</option>
				<option value="Manufactura">Manufactura</option>
				<option value="Servicios">Servicios</option>
				<option value="Otros">Otros</option>
			</select>
			@Html.ValidationMessageFor(Model => Model.Sector)
		</div>
			<br>
			<div class="form-group">
				<input type="submit" value="Guardar" class="btn button" />
				<input type="reset" value="Limpiar" class="btn button" />
			</div>
			}
		</div>

		@section scripts{
			@Scripts.Render("~/bundles/jqueryval");
		}

ApiCliente/Views/Cliente/Index.cshtml
@model IEnumerable<ApiCliente.Models.mvcClienteModel>

@{
	ViewBag.Title = "Menú Clientes";
}
<br>
<h2>Menú Clientes</h2>

<p>
	<a href="@Url.Action("AgregarOEditar", "Cliente")" class="btn btn-default"><i class="fa fa-plus"></i> Agregar Nuevo</a>
</p>
<table class="table table-striped">
	<thead class="table-heading">
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Nombre)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Ced_Juridica)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Pag_Web)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Telefono)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Sector)
			</th>
			<th>Acciones</th>
		</tr>
	</thead>
	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.Nombre)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Ced_Juridica)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Pag_Web)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Telefono)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Sector)
			</td>
			<td>
				<a href="@Url.Action("AgregarOEditar", "Cliente", new { id= item.id})" class="btn btn-default"><i class="fa fa-pencil"></i> Editar</a>
			
				<a Onclick="Delete(@item.id)" class="btn btn-default"><i class="fa fa-trash"></i> Eliminar</a>
			</td>
		</tr>
	}

</table>

@section Scripts {
<script>
	$(function () {
            var successMessage = '@TempData["SuccessMessage"]'
            if (successMessage != '')
                alertify.success(successMessage);
	});
	function Delete(id) {
            alertify.confirm('Web Api CRUD','Realmente desea eliminar el registro ?',function(){
                window.location.href  = '@Url.Action("Eliminar","Cliente")/'+id;
            },null );
    }
</script>
}